//action constants
const LOADED = 'LOADED';
const LOADING_PRODUCT_DETAILS = 'LOADING_PRODUCT_DETAILS';
const LOADED_PRODUCT_DETAILS = 'LOADED_PRODUCT_DETAILS';
const ERROR_PRODUCT_DETAILS = 'ERROR_PRODUCT_DETAILS'


export {
    LOADED,
    LOADING_PRODUCT_DETAILS,
    LOADED_PRODUCT_DETAILS,
    ERROR_PRODUCT_DETAILS
};